.phony: part-one-sample, part-two-sample, part-one, part-two, run, help

part-one-sample:
	@python part_one.py sample_resource.txt

part-one:
	@python part_one.py ../resource.txt

part-two-sample:
	@python part_two.py sample_resource.txt

part-two:
	@python part_two.py ../resource.txt

help:
	@echo "Targets are:"
	@echo "- part-one-sample"
	@echo "- part-one"
	@echo "- part-two-sample"
	@echo "- part-two"

run: help
